// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_tnGHytw-bguZ0_GyMcMDr6mnig-4u20',
    appId: '1:728262744882:web:fe6386c33cdd732a16552b',
    messagingSenderId: '728262744882',
    projectId: 'task-management-b65f1',
    authDomain: 'task-management-b65f1.firebaseapp.com',
    storageBucket: 'task-management-b65f1.firebasestorage.app',
    measurementId: 'G-EVED6LREX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwsbviO0Oh9lQVnLcNiiMLNhtq3Iwl0Kg',
    appId: '1:728262744882:android:4f7c26d15fa2d18f16552b',
    messagingSenderId: '728262744882',
    projectId: 'task-management-b65f1',
    storageBucket: 'task-management-b65f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZlxP2l2vT7iaE7qhA9Zo-580Z6yCrXi8',
    appId: '1:728262744882:ios:e8d8128d115661e116552b',
    messagingSenderId: '728262744882',
    projectId: 'task-management-b65f1',
    storageBucket: 'task-management-b65f1.firebasestorage.app',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZlxP2l2vT7iaE7qhA9Zo-580Z6yCrXi8',
    appId: '1:728262744882:ios:e8d8128d115661e116552b',
    messagingSenderId: '728262744882',
    projectId: 'task-management-b65f1',
    storageBucket: 'task-management-b65f1.firebasestorage.app',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_tnGHytw-bguZ0_GyMcMDr6mnig-4u20',
    appId: '1:728262744882:web:cf2d691db7bd8bc516552b',
    messagingSenderId: '728262744882',
    projectId: 'task-management-b65f1',
    authDomain: 'task-management-b65f1.firebaseapp.com',
    storageBucket: 'task-management-b65f1.firebasestorage.app',
    measurementId: 'G-YM6Q4J6LYT',
  );
}
